[package]
name = "dr-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
url = { version = "2.5.4", features = ["serde"] }
